apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openfaas-gateway-ingress
  namespace: openfaas
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: gateway.localdomain
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 8080
